apiVersion: logging.banzaicloud.io/v1beta1
kind: Output
metadata:
 name: s3-tt-output
spec:
 s3:
   aws_key_id:
     valueFrom:
       secretKeyRef:
         name: logging-s3
         key: awsAccessKeyId
   aws_sec_key:
     valueFrom:
       secretKeyRef:
         name: logging-s3
         key: awsSecretAccessKey
   s3_bucket: appcluster-tekton-logs
   s3_region: us-east-1
   path: tekton-logs/${tag}/%Y/%m/%d/
   buffer:
     timekey: 1m
     timekey_wait: 30s
     timekey_use_utc: true
